server:
  port: 8071

#this property is for git config mapping
spring:
  application:
    name: "configServer"
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/SheyamKumar/microservices-docker-kubernetes.git"
          search-paths: "config_file_path/configs"
          default-label: "master"
          timeout: 5
          clone-on-start: true
          force-pull: true
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

encrypt:
  key: 99223EDEB1525A17F346189D153B2

management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    readiness-state:
      enabled: ture
    liveness-state:
      enabled: ture
  endpoint:
    health:
      probes:
        enabled: ture


# this property is used for class path or file config
#spring:
#  application:
#    name: "configServer"
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          #          search-locations: "classpath:/configs"
#          search-locations: "file:///c://Users//Sheyam Kumar Sakthi//workspace//MicroServices//AccountLoanCardsMS//config_file_path//configs"