build:
  version: "2.0"

accounts:
  message: "Welcome to Banking accounts related QA APIs "
  contactDetails:
    name: "Sheyam - QA Lead"
    email: "Sheyam@123.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371