build:
  version: "3.0"

cards:
  message: "Welcome to Banking cards related APIs "
  contactDetails:
    name: "Sheyam - QA Lead"
    email: "Sheyam@123.com"
  onCallSupport:
    - (412) 419-3491
    - (915) 382-1932
