build:
  version: "1.0"

cards:
  message: "Welcome to Banking cards related prod-1 APIs "
  contactDetails:
    name: "Sheyam Kumar - Product Owner"
    email: "SheyamKumar@123.com"
  onCallSupport:
    - (617) 432-2356
    - (936) 564-8721
