build:
  version: "3.0"

loans:
  message: "Welcome to Banking loans related QA APIs "
  contactDetails:
    name: "Sheyam - Lead"
    email: "Sheyam@123.com"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8934