build:
  version: "1.0"

loans:
  message: "Welcome to Banking loans related QA APIs "
  contactDetails:
    name: "Sheyam - QA Lead"
    email: "Sheyam@123.com"
  onCallSupport:
    - (723) 656-8709
    - (156) 342-0956