build:
  version: "1.0"

accounts:
  message: "Welcome to Banking accounts related Prod APIs "
  contactDetails:
    name: "Sheyam - Owner"
    email: "{chiper}81d13e2b86478debbfe0321b2cd207dda5f9009b81913b031051096ae01c5950"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384