build:
  version: "2.0"

cards:
  message: "Welcome to Banking Cards related QA APIs "
  contactDetails:
    name: "Sheyam - QA Lead"
    email: "sheyam@123.com"
  onCallSupport:
    - (310) 875-4367
    - (201) 236-1267