build:
  version: "2.0"

loans:
  message: "Welcome to Banking loans related QA APIs "
  contactDetails:
    name: "Sheyam - QA Lead"
    email: "Sheyam@123.com"
  onCallSupport:
    - (785) 545-6565
    - (853) 546-3467